//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsportal.User
{


    public partial class Feedback
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox userNameTextbox;
        protected global::System.Web.UI.WebControls.TextBox customernameTextbox;
        protected global::System.Web.UI.WebControls.TextBox mobilenumTextbox;
        protected global::System.Web.UI.WebControls.TextBox requirementTextbox;
        protected global::System.Web.UI.WebControls.TextBox userIdTextbox;
        protected global::System.Web.UI.WebControls.TextBox userName;
    }
}
